### ISSUE TITLE
Heading id generation can create collisions

### ISSUE THREAD

**Issue by sehrgut** [naturalcrit/homebrewery#1430]
## Description

Heading elements are given an id based on a slugified version of the element's innerText. However, this seems to be done without checking for duplicates. This can create invalid HTML that prevents internal links from functioning. Since many headings in a game document might reasonably contain identical text, some strategies for mitigating id collisions are necessary.

**Brew code to reproduce**:

<pre>

# Scary Monsters
### Tarrasque

</pre>

This will result in both `<h2 id='tarrasque'>` and `<h3 id='tarrasque'>` both existing, resulting in neither being a valid anchor target.

Some potential disambiguation strategies:
1. Generate the id from the absolute path through the heading structure
    - The elements in question would then have ids `scary-monsters-tarrasque` and `scary-monsters-tarrasque-tarrasque`, respectively.
    - This the strategy used by GMB, though they generate the same id on the enclosing `<section>` too, so their TOCs are even more broken.
2. Append a serial number.
    - The first strategy will handle most instances in most documents, simply due to the domain conventions of game publications. It's unlikely two sibling headings will have the same text.
    - This wouldn't be a good strategy for a primary disambiguator, since it will change be less stable to document rearrangement.
    - However, as a fallback after the first strategy still generates a duplicate, I think it would be useful.

Not sure if this is a feature request or a real bug, though I'm leaning to the latter since it results in invalid HTML output.

**Comment by calculuschild** [comment]
The sluggified IDs are generated using our Markdown library, Marked.js. this might be something we can fix over there.

**Comment by sehrgut** [comment]
I wonder if it's something to do with how the document is fragmented for rendering, which might not preserve existing header IDs from earlier contexts. However, all I'm seeing is fragmenting by page, so while that could be another issue, it shouldn't be relevant to this minimal repro.

**Comment by ericscheid** [comment]
Page fragmenting is not the issue.

This produces the same id for all 3 headings. 
```
# Heading
## Heading
\page
# Heading
```

**Comment by Gazook89** [comment]
> Page fragmenting is not the issue.  This produces the same id for all 3 headings.

I don't think this is true, at least any more.  The headings on the same page get different IDs (numbered suffix).   So this is only a problem between pages at this point.  I don't know if that's due to some change we made, or in Marked.js.  

So with the issue somehow resolved intra-page, it's only an issue across pages; it's back to this:

> I wonder if it's something to do with how the document is fragmented for rendering, which might not preserve existing header IDs from earlier contexts.

So perhaps an extra step after rendering that just resets header ids?

**Comment by 5e-Cleric** [comment]
This should be fixed with #3156

**Comment by sehrgut** [comment]
Wootsauce! Thank you!

**Comment by calculuschild** [comment]
Sorry, this one isn't quite solved. Wr made some progress but haven't quite finished.

**Comment by 5e-Cleric** [comment]
Right, now it should be fixed.
