### ISSUE TITLE
Getting the current Editor Page for page rendering happens out of sync

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#3317]
See #3000 which fixes the symptom but not the root cause.

The error is caused by the addition of this line:

https://github.com/naturalcrit/homebrewery/blob/4feeaee7e779391bbfe4de61c786864b408ddac9/client/homebrew/brewRenderer/brewRenderer.jsx#L155

This line is to make sure when rendering pages, we always render the currently-edited page first (which may not be in view on the brewRenderer preview). This ensures that any changes that have cross-page effects (e.g. variables or links) have their changes propagated correctly to the pages in view.

Unfortunately, updating the "current editor page" happens slightly out of sync here:

Codemirror sees a change -> sends this change up to the top at `handleTextChange()` in `editPage.jsx` (or `newPage` or `homePage`) and gets the currently edited page from `editor.jsx` -> propagates new text down to `editor.jsx` and `brewRenderer.jsx`.

As you can see, `editor.jsx` is being asked to calculate the latest cursor position before it it has received the latest text.

https://github.com/naturalcrit/homebrewery/blob/4feeaee7e779391bbfe4de61c786864b408ddac9/client/homebrew/pages/editPage/editPage.jsx#L116

So while this PR does fix the crashing (I will merge this for now), it might be worth moving `getCurrentPage()` to come directly from Codemirror in `codeEditor.jsx` instead which will be more accurate.

**Comment by dbolack-ab** [comment]
I believe this has been fixed by somewhat recent code as part of the spread view.

**Comment by 5e-Cleric** [comment]
The issue still stands, showing only in some screens, not sure why. I get the issue in one of my screens, not the other.

**Comment by dbolack-ab** [comment]
Are we still seeing this?

**Comment by 5e-Cleric** [comment]
After an entire year i have no idea of what i was seeing, but it was obviously inconsistent, tagging @calculuschild just in case he has a better memory than i do.

**Comment by 5e-Cleric** [comment]
I think this is fixed. Is it not? @calculuschild

**Comment by 5e-Cleric** [comment]
Closing without response
