### ISSUE TITLE
Top of snippetBar is hidden when using Ctrl+F in Codemirror section

### ISSUE THREAD

**Issue by telboy007** [naturalcrit/homebrewery#4098]
### Renderer

v3.18.0

### Browser

Chrome Version 134.0.6998.89 (Official Build) (arm64))

### Operating System

MacOS (14.2.1 (23C71))

### What happened?

If you ctrl+f in the code or style part of the editor the top nav of the snippetBar nav gets hidden and can't be clicked (which makes moving between code and style impossible).

NOTE: This doesn't happen when the snippetBar is one row, only when it's over two rows (due to screen res / position of divider).

<img width="594" alt="Image" src="https://github.com/user-attachments/assets/ecad33ba-b836-45b1-a544-64cdc9da8065" />
<img width="584" alt="Image" src="https://github.com/user-attachments/assets/c6f635e4-7985-4224-a77c-608c7bac211d" />

This can be rectified by refreshing the page.

**Comment by 5e-Cleric** [comment]
I cannot replicate this issue as of today in Windows 11 and Chrome 134. Will test further.

Can you share Full screen shots please?

**Comment by telboy007** [comment]
Thought it would be easier to video the behaviour and upload to youtube.
https://www.youtube.com/watch?v=Lw5CYdDPx3U

**Comment by 5e-Cleric** [comment]
Ok, great, can replicate the issue, which means i'll find a fix.

For the future, you can also upload the video here.

**Comment by 5e-Cleric** [comment]
The easiest way to find the bug is to:

1. have an editor that does not have lines outside of the page
2. Put new lines in the editor until you cause overflow

and voila.

I have a fix in place for this, in the linked PR.

**Comment by telboy007** [comment]
> For the future, you can also upload the video here.

Computer said no! (don't think it liked .mov files)

**Comment by 5e-Cleric** [comment]
this is somehow back in my local install, not sure why, maybe i fixed it wrong.

**Comment by 5e-Cleric** [comment]
This issue is back again, i'm at a total loss here.

**Comment by calculuschild** [comment]
> This issue is back again, i'm at a total loss here.

This wasn't released live yet. Is the issue still on staging?

**Comment by 5e-Cleric** [comment]
> > This issue is back again, i'm at a total loss here.
> 
> @5e-Cleric This wasn't released live yet. I don't see the issue on staging, but live doesn't have the fix yet.
> 
> Do you see the issue on staging?

I did a week ago, i'll check again

**Comment by 5e-Cleric** [comment]
Alright, this shoulld be completely fixed.
