### ISSUE TITLE
Broken FontAwesome Icons on Account Page

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#4367]
It appears that when Font Awesome was updated to v6.0, the icons for the selected storage location on the Account Page were not updated - to be clear, they were updated to use Font Awesome v6.0, but the actual icons were not updated to point at icons that exist in the new font set.

<img width="359" height="138" alt="Image" src="https://github.com/user-attachments/assets/8c1c5e4d-2c0f-4b85-a4fa-be8c0f577357" />

<img width="354" height="144" alt="Image" src="https://github.com/user-attachments/assets/d6c4e024-5eee-4760-a113-58959bd6da76" />

<img width="489" height="114" alt="Image" src="https://github.com/user-attachments/assets/11aa8f76-3d5d-4929-8377-61028855cba0" />

Should be a simple fix to resolve - in the appropriate CSS styling block, the `\f00c` needs to be changed to an appropriate value - I believe that previously the icon was a tick/check mark.

**Comment by G-Ambatte** [comment]
On further investigation, it is not that the _content_ is incorrect, but rather that the _weight_ is not set correctly.

<img width="519" height="108" alt="Image" src="https://github.com/user-attachments/assets/3c1b613b-3bac-4105-8143-bbed02e21f7f" />

<img width="351" height="143" alt="Image" src="https://github.com/user-attachments/assets/bce3280a-4f4c-4f3a-817d-6c134041b8ac" />

Simply adding `font-weight: 900;` to the appropriate styling block will resolve this issue.

**Comment by Gazook89** [comment]
Pretty sure same issue is elsewhere too. BrewItem too.

**Comment by dbolack-ab** [comment]
This appears to have been fixed.

**Comment by 5e-Cleric** [comment]
I still see the issue, unless we made it in the last patch...

**Comment by dbolack-ab** [comment]
I'm just looking at the less file and running local

**Comment by G-Ambatte** [comment]
PR #4368 has been merged, which has corrected this issue. Looks like I forgot to link the resolving PR to this issue.

Closing.
