### ISSUE TITLE
Table decoration split between columns

### ISSUE THREAD

**Issue by NoelMock** [naturalcrit/homebrewery#620]
I am trying to align my class table on the second column, but no matter what I do, it will not shift at all. The top of the table prints on the bottom of the left column, while the rest prints on the right column.

### Additional Details

**http://homebrewery.naturalcrit.com/share/H1Wazfkcef** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by DoctorDan1986** [comment]
Use a column break to force it into the next column (under editor), and it's best not to post the edit link. Use the share link next time.

**Comment by NoelMock** [comment]
Thanks. I tried using the column break, but then it created a whole empty column and pushed the table and text off the page.  (Because the text in column 1 goes all the way to the bottom.

**Comment by granack** [comment]
yeah, table decoration doesn't go to the next column. it's annoying, and I'm not sure if it's a homebrewery issue or css in general. To fix it, you need something to render, like a non-breaking space, at the top of the page, so between the column break and the table `<div>`. Adjust the `<div>` margin to bring it up a bit since the extra bit will push it down.
Basically, do this:

    ```
    ```
    &nbsp;
    <div class='classTable' style="margin-top: 0px">

for reference, the default margin is somewhere around 25px.
I use lots of `&nbsp;` and margin adjustments to get my stuff working just right.

**Comment by NoelMock** [comment]
Thanks! It at least prints okay now... :)

**Comment by ericscheid** [comment]
Recreating from the source of the shared brew I see a different but related problem (the table is put into column-2 by virtue of column-1 being full).

![image](https://user-images.githubusercontent.com/2605467/99152893-cc85d580-26f8-11eb-8689-4653ad3ef6e0.png)

> I am trying to align my class table on the second column, but no matter what I do, it will not shift at all. The top of the table prints on the bottom of the left column, while the rest prints on the right column.

Was there a recent change that attempted to fix this .. because it looks like it did, but created a new problem.

----

I have also seen in the past where a blockquote note is at the bottom of column 1, but the overhanging bottom border is at the top of column 2. Attempting to recreate (using `<div style="margin-top:1px"></div>` to nudge it downwards .. and I see the overhang border disappear, but no longer re-appears at top of column 2.

**Comment by Gazook89** [comment]
This was fixed with #1179 at the beginning of the year.  closing.

**Comment by calculuschild** [comment]
This is still an issue. The solution `TranslateZ(0)` caused other issues (nested items disappearing, etc) so we had to undo it.

**Comment by calculuschild** [comment]
Closing. This was fixed with Chrome v102.
